language: generic

before_install:
  - sudo apt-get install texlive-binaries

install:
  - export PATH="$HOME/miniconda/bin:$PATH"
  - if ! command -v conda > /dev/null; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda -u;
      conda config --add channels conda-forge;
      conda config --set always_yes yes;
      conda install tectonic==0.1.10;
    fi
  - conda install -c malramsay biber==2.5 --yes
  - conda info -a
  # Workaround until tectonic 0.1.11 is available
  - sudo mkdir -p ~/.config/Tectonic/
  - echo "[[default_bundles]]" | sudo tee --append ~/.config/Tectonic/config.toml
  - sudo echo "url = \"https://tectonic.newton.cx/bundles/tlextras-2018.1r0/bundle.tar\"" | sudo tee --append ~/.config/Tectonic/config.toml
cache:
  directories:
    - $HOME/miniconda
    - $HOME/.cache/Tectonic
script: 
 - tectonic --keep-intermediates --reruns 0 ./cv_MarcoDenisi.tex
 - tectonic ./cv_MarcoDenisi.tex --print
deploy:
  provider: releases
  file: 
    - "cv_MarcoDenisi.pdf"
  skip_cleanup: true
  on:
    tags: true
    branch: master