language: r
sudo: true
latex: false
pandoc: false
warnings_are_errors: false
install: echo "The install step is required but does nothing now."
script:
- Rscript install_texlive.R
- Rscript -e 'tinytex::pdflatex("cv_MarcoDenisi.tex", bib_engine = "biber")'
deploy:
  provider: releases
  file:
  - cv_MarcoDenisi.pdf
  skip_cleanup: true
  on:
    tags: true
    branch: master
  api_key:
    secure: JGwIcUbx6LR9G01sMlkYf9vusWqEkY0C1/4S3+cTtjosuSG1jjTr/2O3GP6UPK/VqfVzbUiJygULXg3xkHT2BqQ+mwmrsq6KCafQJfViNz3K94cllAETcCPVBIbqiTz2QNREe/OhrHUVDMbRjVzuig7x7MUbLPfiyZoxxHn5dkEn5Ls24T0ILi3GjeQw4JzcW1rmFz98OOdK1apH00Y/eexEXxxihTC+qHZuG4fDuWPZesb9VA8jPYyLEeRVoZWSNYdLbFYh9/Kruu4sHzFF+ptEu8X9ossX3seUBJ8rBk2hLASVO1NFkrxXygE/Wd1uosqoUXsbdCf8DcfKnAZvkWbVjZYWRyalo8BCslYKYXkPFN9cxTycaO2nilkq9I0vwhf11QwJ7+8UUvD34C8/V6TCE+jpQ5nf2Oum+1EE0hiC+Ru6puDkloIn3tCQ2UI6ggPwTwH5FHfg3aiH3cp/rASP7vh6boQBKVveSqLlhXOdUsNxSDkEvyGM033PpLyoL3yQjEcFoeOGtrrPwfW85xoycMfS808JljnwGX7H07KkL8Mq5ZJCWLlCXzKI0nao/H3L2rfPjcu0Ym/R5a1I8BAWon1h6cQFtZDbp0TMtXi6GYjT7hm1xDy0kyj6DnI/BeVWHGoSHH6KgQSw34ytiVPlrzJ8/0wCgC9s8eMFVcc=
