name: Build CV
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  release_cv:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v1
    - name: Compile CV
      uses: xu-cheng/latex-action@master
      with:
        root_file: cv_MarcoDenisi.tex
    - name: Check pdf file
      run: |
        file cv_MarcoDenisi.pdf | grep -q ' PDF '
    - name: Create and upload release
      uses: softprops/action-gh-release@v1
      with:
        files: cv_MarcoDenisi.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}